import type { NextPage } from 'next';
import Head from 'next/head';
import { useRecoilValue } from 'recoil';
import Header from '../components/index-page/Header';
import ProductRequest from '../components/global/ProductRequest';
import Toolbar from '../components/index-page/Toolbar';
import { productRequestState } from '../lib/atoms';
import { categoryProductRequestState } from '../lib/selectors';
import useGetStatusCount from '../lib/hooks/useGetStatusCount';
import NoFeedbackCard from '../components/index-page/NoFeedbackCard';

const Home: NextPage = () => {
  const productRequests = useRecoilValue(productRequestState);
  const { statusCount } = useGetStatusCount(productRequests);
  const filteredRequestList = useRecoilValue(categoryProductRequestState);

  return (
    <div className='bg-text-grey min-h-screen'>
      <div className=' flex flex-col lg:flex-row lg:gap-x-7 lg:px-16 lg:pt-28 xl:max-w-[1110px] xl:m-auto'>
        <Head>
          <title>Product Feedback App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon-32x32.png' />
        </Head>
        <Header statusCount={statusCount} />
        <main className=' sm:px-10 lg:px-0 pb-14'>
          <Toolbar suggestionAmount={productRequests.length} />
          <div className='px-6 pt-8 sm:px-0 grid grid-cols-1 gap-4'>
            {filteredRequestList &&
              filteredRequestList.map((request) => (
                <ProductRequest key={request.id} request={request} />
              ))}
            {filteredRequestList?.length === 0 && <NoFeedbackCard />}
          </div>
        </main>
      </div>
    </div>
  );
};

export default Home;
